// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/microhq/profile-srv/proto/record/record.proto

/*
Package record is a generated protocol buffer package.

It is generated from these files:
	github.com/microhq/profile-srv/proto/record/record.proto

It has these top-level messages:
	Profile
	CreateRequest
	CreateResponse
	DeleteRequest
	DeleteResponse
	ReadRequest
	ReadResponse
	UpdateRequest
	UpdateResponse
	SearchRequest
	SearchResponse
*/
package record

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Profile struct {
	Id          string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Owner       string `protobuf:"bytes,3,opt,name=owner" json:"owner,omitempty"`
	Type        int64  `protobuf:"varint,4,opt,name=type" json:"type,omitempty"`
	DisplayName string `protobuf:"bytes,6,opt,name=displayName" json:"displayName,omitempty"`
	Blurb       string `protobuf:"bytes,7,opt,name=blurb" json:"blurb,omitempty"`
	Url         string `protobuf:"bytes,8,opt,name=url" json:"url,omitempty"`
	Location    string `protobuf:"bytes,9,opt,name=location" json:"location,omitempty"`
	Created     int64  `protobuf:"varint,10,opt,name=created" json:"created,omitempty"`
	Updated     int64  `protobuf:"varint,11,opt,name=updated" json:"updated,omitempty"`
}

func (m *Profile) Reset()                    { *m = Profile{} }
func (m *Profile) String() string            { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()               {}
func (*Profile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Profile) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Profile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Profile) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Profile) GetType() int64 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Profile) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Profile) GetBlurb() string {
	if m != nil {
		return m.Blurb
	}
	return ""
}

func (m *Profile) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Profile) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Profile) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Profile) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

type CreateRequest struct {
	Profile *Profile `protobuf:"bytes,1,opt,name=profile" json:"profile,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateRequest) GetProfile() *Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

type CreateResponse struct {
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type DeleteRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *DeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteResponse struct {
}

func (m *DeleteResponse) Reset()                    { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()               {}
func (*DeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type ReadRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ReadRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadResponse struct {
	Profile *Profile `protobuf:"bytes,1,opt,name=profile" json:"profile,omitempty"`
}

func (m *ReadResponse) Reset()                    { *m = ReadResponse{} }
func (m *ReadResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()               {}
func (*ReadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ReadResponse) GetProfile() *Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

type UpdateRequest struct {
	Profile *Profile `protobuf:"bytes,1,opt,name=profile" json:"profile,omitempty"`
}

func (m *UpdateRequest) Reset()                    { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()               {}
func (*UpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *UpdateRequest) GetProfile() *Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

type UpdateResponse struct {
}

func (m *UpdateResponse) Reset()                    { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()               {}
func (*UpdateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type SearchRequest struct {
	Name   string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Owner  string `protobuf:"bytes,2,opt,name=owner" json:"owner,omitempty"`
	Limit  int64  `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
	Offset int64  `protobuf:"varint,4,opt,name=offset" json:"offset,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *SearchRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SearchRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *SearchRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *SearchRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type SearchResponse struct {
	Profiles []*Profile `protobuf:"bytes,1,rep,name=profiles" json:"profiles,omitempty"`
}

func (m *SearchResponse) Reset()                    { *m = SearchResponse{} }
func (m *SearchResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()               {}
func (*SearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *SearchResponse) GetProfiles() []*Profile {
	if m != nil {
		return m.Profiles
	}
	return nil
}

func init() {
	proto.RegisterType((*Profile)(nil), "Profile")
	proto.RegisterType((*CreateRequest)(nil), "CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "CreateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "DeleteResponse")
	proto.RegisterType((*ReadRequest)(nil), "ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "ReadResponse")
	proto.RegisterType((*UpdateRequest)(nil), "UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "UpdateResponse")
	proto.RegisterType((*SearchRequest)(nil), "SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "SearchResponse")
}

func init() {
	proto.RegisterFile("github.com/microhq/profile-srv/proto/record/record.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 454 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xe1, 0x8a, 0xd3, 0x40,
	0x10, 0x6e, 0x9a, 0x5e, 0xda, 0x9b, 0x5e, 0xd2, 0x63, 0x38, 0x64, 0x09, 0x88, 0x25, 0x28, 0x1c,
	0x88, 0x5b, 0x68, 0x41, 0xfc, 0xaf, 0xbf, 0x45, 0x22, 0x3e, 0x40, 0x9a, 0x6c, 0xaf, 0x0b, 0x69,
	0x37, 0xb7, 0x49, 0x94, 0x7b, 0x5e, 0x9f, 0xc0, 0x37, 0x90, 0x9d, 0xdd, 0xad, 0x4d, 0x51, 0xf0,
	0x7e, 0x75, 0xbe, 0x99, 0x6f, 0x26, 0x33, 0xdf, 0xb7, 0x85, 0x0f, 0x0f, 0xb2, 0xdb, 0xf7, 0x5b,
	0x5e, 0xaa, 0xc3, 0xea, 0x20, 0x4b, 0xad, 0xf6, 0x8f, 0xab, 0x46, 0xab, 0x9d, 0xac, 0xc5, 0xbb,
	0x56, 0x7f, 0x37, 0x71, 0xa7, 0x56, 0x5a, 0x94, 0x4a, 0x57, 0xee, 0x87, 0x53, 0x2e, 0xfb, 0x15,
	0xc0, 0xf4, 0x8b, 0x65, 0x62, 0x02, 0x63, 0x59, 0xb1, 0x60, 0x19, 0xdc, 0x5f, 0xe7, 0x63, 0x59,
	0x21, 0xc2, 0xe4, 0x58, 0x1c, 0x04, 0x1b, 0x53, 0x86, 0x62, 0xbc, 0x83, 0x2b, 0xf5, 0xe3, 0x28,
	0x34, 0x0b, 0x29, 0x69, 0x81, 0x61, 0x76, 0x4f, 0x8d, 0x60, 0x93, 0x65, 0x70, 0x1f, 0xe6, 0x14,
	0xe3, 0x12, 0xe6, 0x95, 0x6c, 0x9b, 0xba, 0x78, 0xfa, 0x6c, 0x86, 0x44, 0xc4, 0x3f, 0x4f, 0x99,
	0x59, 0xdb, 0xba, 0xd7, 0x5b, 0x36, 0xb5, 0xb3, 0x08, 0xe0, 0x2d, 0x84, 0xbd, 0xae, 0xd9, 0x8c,
	0x72, 0x26, 0xc4, 0x14, 0x66, 0xb5, 0x2a, 0x8b, 0x4e, 0xaa, 0x23, 0xbb, 0xa6, 0xf4, 0x09, 0x23,
	0x83, 0x69, 0xa9, 0x45, 0xd1, 0x89, 0x8a, 0x01, 0x7d, 0xdc, 0x43, 0x53, 0xe9, 0x9b, 0x8a, 0x2a,
	0x73, 0x5b, 0x71, 0x30, 0xdb, 0x40, 0xfc, 0x91, 0x48, 0xb9, 0x78, 0xec, 0x45, 0xdb, 0x61, 0x06,
	0x53, 0xa7, 0x16, 0x5d, 0x3f, 0x5f, 0xcf, 0xb8, 0xd3, 0x24, 0xf7, 0x85, 0xec, 0x16, 0x12, 0xdf,
	0xd4, 0x36, 0xea, 0xd8, 0x8a, 0xec, 0x15, 0xc4, 0x9f, 0x44, 0x2d, 0xfe, 0x8c, 0xb9, 0xd0, 0xcf,
	0xb4, 0x78, 0x82, 0x6b, 0x79, 0x09, 0xf3, 0x5c, 0x14, 0xd5, 0xbf, 0x1a, 0xd6, 0x70, 0x63, 0xcb,
	0x96, 0xfe, 0x5f, 0x7b, 0x6d, 0x20, 0xfe, 0x46, 0x77, 0x3d, 0xf3, 0x18, 0xdf, 0xe4, 0x36, 0x7b,
	0x80, 0xf8, 0xab, 0x28, 0x74, 0xb9, 0xf7, 0x63, 0xbc, 0xf9, 0xc1, 0xdf, 0xcc, 0x1f, 0x9f, 0x9b,
	0x7f, 0x07, 0x57, 0xb5, 0x3c, 0xc8, 0x8e, 0x9e, 0x44, 0x98, 0x5b, 0x80, 0x2f, 0x20, 0x52, 0xbb,
	0x5d, 0x2b, 0x3a, 0xf7, 0x28, 0x1c, 0xca, 0xde, 0x43, 0xe2, 0x3f, 0xe4, 0xae, 0x7c, 0x0d, 0x33,
	0xb7, 0x57, 0xcb, 0x82, 0x65, 0x38, 0xd8, 0xf8, 0x54, 0x59, 0xff, 0x0c, 0x20, 0xca, 0xe9, 0xe5,
	0xe2, 0x5b, 0x88, 0xac, 0x15, 0x98, 0xf0, 0x81, 0x91, 0xe9, 0x82, 0x5f, 0x78, 0x34, 0xc2, 0x37,
	0x30, 0x31, 0x9a, 0xe2, 0x0d, 0x3f, 0x53, 0x3e, 0x8d, 0xf9, 0xb9, 0xd0, 0xd9, 0xc8, 0xcc, 0xb4,
	0x5e, 0x61, 0xc2, 0x07, 0xae, 0xa6, 0x0b, 0x7e, 0x61, 0x22, 0x91, 0xad, 0x7c, 0x98, 0xf0, 0x81,
	0xf8, 0xe9, 0x82, 0x5f, 0xe8, 0x4a, 0x64, 0x7b, 0x30, 0x26, 0x7c, 0x20, 0x71, 0xba, 0xe0, 0x43,
	0x25, 0xb2, 0xd1, 0x36, 0xa2, 0x7f, 0xe5, 0xe6, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf7, 0xcd,
	0xd9, 0x70, 0xd1, 0x03, 0x00, 0x00,
}
